### ISSUE TITLE
Fails with international characters

### ISSUE THREAD

**Issue by fire-eggs** [juvalen/mb-checker#3]
A useful program, except both scripts fail with `UnicodeDecodeError`. The culprit bookmark from my file is below.

In both scripts, the fix is to change every instance of the `open()` call to specify utf-8 encoding. For one example in scanJson.py change this line:
```
with open(JSONIN, "r") as f:
```
to this:
```
with open(JSONIN, "r", encoding='utf-8') as f:
```

Also, the last line in buildJSON.py needs to be changed to read:
```
    json.dump(filtered , fout, sort_keys=True, ensure_ascii=False, indent=4, separators=(',', ': '))
```

Ideally, every `open()` call needs to be changed so the international characters are preserved correctly during the scan and filtering. However, I have not seen any problems as long as the two open() calls for the bookmarks file, and the json.dump() call above, are changed.

Here is the JSON for the breaking bookmark:
```
{
                        "date_added": "13160007124000000",
                        "id": "1627",
                        "name": "Programy pro genealogii: GEDmill, genealogický program, chybí čeština",
                        "type": "url",
                        "url": "https://genealogie-sw.blogspot.com/2013/10/gedmill-genealogicky-program-chybi.html"
                     }
```

**Comment by juvalen** [comment]
Updated
Thanks
