### ISSUE TITLE
All bookmarks in "Other Bookmarks" are thrown away

### ISSUE THREAD

**Issue by fire-eggs** [juvalen/mb-checker#4]
As written, scanJSON.py only examines the bookmarks in the Bookmarks Bar. All bookmarks in "Other bookmarks" are not examined, and effectively filtered away.

This line:
```
original = Bookmarks['roots']['bookmark_bar']['children']
```
limits the search to the bookmark bar. The "Other Bookmarks" would be included with the line:
```
others = Bookmarks['roots']['other']['children']
```
except I have no idea how to merge the two together.

**Comment by juvalen** [comment]
I will make scanJSON.py create also other.url & synced.url files and merge them in buildJSON.py

**Comment by juvalen** [comment]
No extra intermediate files used

Now "other" & "synced" folders filtered to output/Filtered.json also
